pipeline:
  build:
    image: appleboy/drone-ssh
    pull: true
    host: ${HOST}
    user: ${USER}
    #key: ${SSH_KEY}
    password: ${PASS}
    port: 22
    command_timeout: 180
    commands:
      - env
    script:
      - sudo yum install docker
      - sudo systemctl start docker
      - sudo docker stop flask_cont
      - sudo docker rm flask_cont
      - sudo docker rmi flask_image
      - cd /tmp/
      - rm -rf cicd-learn
      - sudo git clone https://github.com/pkumarbe/cicd-learn.git
      - sudo cd /tmp/cicd-learn/
      - sudo docker build -t flask_image /tmp/cicd-learn/
      - sudo docker run -dti --name flask_cont -p 8001:8001 flask_image
    when:
      event: push
  publish:
    image: plugins/docker
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    email: mymail8500@gmail.com
    repo: pk1dockerhub/cicd_drone_img
    tag: latest
    file: Dockerfile
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    when:
        event: push
